export type ServicoStatus = 'fazendo' | 'a-fazer' | 'em-breve'

export interface ServicoData {
  iconName: string
  label: string
  desc: string
  color: string
  badge: string
  badgeBg: string
  badgeColor: string
  status: ServicoStatus
  statusLabel: string
  btnLabel: string
  btnHref?: string
}

export const SERVICOS: ServicoData[] = [
  {
    iconName: 'FileText',
    label: 'Texto',
    desc: 'Escreva e edite o conteúdo do seu livro com IA',
    color: '#f97316',
    badge: 'FAZENDO',
    badgeBg: 'rgba(249,115,22,0.15)',
    badgeColor: '#f97316',
    status: 'fazendo',
    statusLabel: 'Plano pronto',
    btnLabel: 'Abrir Editor',
  },
  {
    iconName: 'Palette',
    label: 'Capas',
    desc: 'Uma capa profissional atrai mais leitores!',
    color: '#a855f7',
    badge: 'A FAZER',
    badgeBg: 'rgba(168,85,247,0.12)',
    badgeColor: '#a855f7',
    status: 'a-fazer',
    statusLabel: 'Não iniciado',
    btnLabel: 'Criar minha capa',
  },
  {
    iconName: 'ImageIcon',
    label: 'Ilustrações',
    desc: 'Ilustrações dão vida à sua história!',
    color: '#f59e0b',
    badge: 'A FAZER',
    badgeBg: 'rgba(245,158,11,0.12)',
    badgeColor: '#f59e0b',
    status: 'a-fazer',
    statusLabel: 'Não iniciado',
    btnLabel: 'Ilustrar capítulos',
  },
  {
    iconName: 'Globe',
    label: 'Publicação',
    desc: 'Prepare tudo para publicar seu livro no mundo!',
    color: '#22d3ee',
    badge: 'A FAZER',
    badgeBg: 'rgba(34,211,238,0.12)',
    badgeColor: '#22d3ee',
    status: 'a-fazer',
    statusLabel: 'Não iniciado',
    btnLabel: 'Preparar publicação',
  },
  {
    iconName: 'Megaphone',
    label: 'Kit de Marketing',
    desc: 'Posts prontos pra Instagram, e-mails e banners — só copiar e postar.',
    color: '#ec4899',
    badge: 'A FAZER',
    badgeBg: 'rgba(236,72,153,0.12)',
    badgeColor: '#ec4899',
    status: 'a-fazer',
    statusLabel: 'Não iniciado',
    btnLabel: 'Pegar meus materiais',
  },
  {
    iconName: 'Rocket',
    label: 'Plano de Lançamento',
    desc: 'Plano dia-a-dia D-30 → D-0: posts, Amazon KDP, imprensa e influenciadores.',
    color: '#f59e0b',
    badge: 'EM BREVE',
    badgeBg: 'rgba(168,85,247,0.12)',
    badgeColor: '#a855f7',
    status: 'em-breve',
    statusLabel: 'Em breve',
    btnLabel: 'Planejar meu lançamento',
  },
  {
    iconName: 'Headphones',
    label: 'Audiobook',
    desc: 'Alcance leitores que preferem ouvir histórias!',
    color: '#4f7fff',
    badge: 'A FAZER',
    badgeBg: 'rgba(79,127,255,0.12)',
    badgeColor: '#4f7fff',
    status: 'a-fazer',
    statusLabel: 'Não iniciado',
    btnLabel: 'Criar audiobook',
  },
  {
    iconName: 'ShoppingCart',
    label: 'Vender',
    desc: 'Monetize seu livro nas principais plataformas de venda.',
    color: '#22d3ee',
    badge: 'A FAZER',
    badgeBg: 'rgba(34,211,238,0.12)',
    badgeColor: '#22d3ee',
    status: 'a-fazer',
    statusLabel: 'Não iniciado',
    btnLabel: 'Começar a vender',
  },
  {
    iconName: 'Languages',
    label: 'Tradução',
    desc: 'Leitores do mundo inteiro podem ler seu livro!',
    color: '#a855f7',
    badge: 'A FAZER',
    badgeBg: 'rgba(168,85,247,0.12)',
    badgeColor: '#a855f7',
    status: 'a-fazer',
    statusLabel: 'Não iniciado',
    btnLabel: 'Traduzir agora',
  },
  {
    iconName: 'BookMarked',
    label: 'Registro de ISBN',
    desc: 'Documentação oficial e registro da sua obra.',
    color: '#f97316',
    badge: 'A FAZER',
    badgeBg: 'rgba(249,115,22,0.12)',
    badgeColor: '#f97316',
    status: 'a-fazer',
    statusLabel: 'Não iniciado',
    btnLabel: 'Registrar ISBN',
  },
  {
    iconName: 'FileCheck',
    label: 'Ficha Catalográfica',
    desc: 'Ficha catalográfica obrigatória para publicação.',
    color: '#a855f7',
    badge: 'A FAZER',
    badgeBg: 'rgba(168,85,247,0.12)',
    badgeColor: '#a855f7',
    status: 'a-fazer',
    statusLabel: 'Não iniciado',
    btnLabel: 'Gerar ficha',
  },
]
